/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aeropuerto;

import com.lap.dao.AeropuertoImpl;
import com.lap.dto.AeropuertoDTO;

import java.util.List;

/**
 *
 * @author luisgarcia
 */
public class JFAero extends javax.swing.JFrame {

    /**
     * Creates new form JFAero
     */
    public JFAero() {
        initComponents();
        jTcodigo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTcodigo = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jTciudad = new javax.swing.JTextField();
        jTpais = new javax.swing.JTextField();
        jBinsertar = new javax.swing.JButton();
        jBconsultar = new javax.swing.JButton();
        jBactualizar = new javax.swing.JButton();
        jBVerTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAtodo = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo :");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Ciudad :");

        jLabel4.setText("Pais:");

        jTcodigo.setColumns(3);
        jTcodigo.setText(" ");

        jTnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnombreActionPerformed(evt);
            }
        });

        jBinsertar.setText("Insertar");
        jBinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinsertarActionPerformed(evt);
            }
        });

        jBconsultar.setText("Consultar");
        jBconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultarActionPerformed(evt);
            }
        });

        jBactualizar.setText("Actualizar");
        jBactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBactualizarActionPerformed(evt);
            }
        });

        jBVerTodo.setText("Ver Todo");
        jBVerTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerTodoActionPerformed(evt);
            }
        });

        jTAtodo.setColumns(20);
        jTAtodo.setRows(5);
        jScrollPane1.setViewportView(jTAtodo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTnombre))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 115, Short.MAX_VALUE)
                                .addComponent(jBVerTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBinsertar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBconsultar)
                                .addGap(1, 1, 1))
                            .addComponent(jBactualizar))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBconsultar))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBactualizar)
                    .addComponent(jBinsertar)
                    .addComponent(jBVerTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnombreActionPerformed

    private void jBVerTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerTodoActionPerformed
        // TODO add your handling code here:
        AeropuertoImpl impl = new AeropuertoImpl(); 
        
        
        List<AeropuertoDTO> aeropuertos=impl.getAllAeropuertos();
        
        // por eficiencia en vez de usar un String utilizamos la clase StringBuilder
        StringBuilder sb= new StringBuilder();
        
        for(int i=0;i<aeropuertos.size();i++){
            AeropuertoDTO dto = aeropuertos.get(i);
            
            sb.append(dto.getCodigo());
            sb.append("\t");
            sb.append(dto.getNombre());
            sb.append("\t");
            sb.append(dto.getCiudad());
            sb.append("\t");
            sb.append(dto.getPais());
            sb.append("\n");
            
        }
        
        jTAtodo.setText(sb.toString());
    }//GEN-LAST:event_jBVerTodoActionPerformed

    private void jBinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinsertarActionPerformed
        // TODO add your handling code here:
        
        // 1. recuperamos los datos ingresados y los almacenamos en un DTO
        String codigo = jTcodigo.getText();
        String nombre = jTnombre.getText();
        String ciudad = jTciudad.getText();
        String pais = jTpais.getText();
        
        AeropuertoDTO objAeropuerto = new AeropuertoDTO();
        objAeropuerto.setCodigo(codigo);
        objAeropuerto.setNombre(nombre);
        objAeropuerto.setCiudad(ciudad);
        objAeropuerto.setPais(pais);
        
        // 2. invocamos el metodo insertar
        AeropuertoImpl impl = new AeropuertoImpl(); 
        int res=impl.insertaAeropuerto(objAeropuerto);
        
        // 2. insertamos un nuevo aeropuerto
        
        if(res==1){
            jTAtodo.setText("registro exitoso!");
        }
        
        
        
    }//GEN-LAST:event_jBinsertarActionPerformed

    private void jBconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultarActionPerformed
        // TODO add your handling code here:
        
        // 1. recuperamos el codigo de aeropuerto ingresado
        
        String codigo = jTcodigo.getText();
        System.out.println(codigo);
        
        // 2. invocamos el metodo getAeropuerto de nuestra clase utilitaria de acceso a base de datos
        // AeropuertoImpl
        AeropuertoImpl impl = new AeropuertoImpl(); 
        AeropuertoDTO objAeropuerto =  impl.getAeropuerto(codigo);
                      
        // 3. Mostramos en pantalla los datos recuperados en objAeropuerto
        
        if (objAeropuerto.getNombre()!=null){ // si el objeto aeropuerto tiene datos 
            
            jTnombre.setText(objAeropuerto.getNombre());
            jTciudad.setText(objAeropuerto.getCiudad());
            jTpais.setText(objAeropuerto.getPais());
        }
        
                              
    }//GEN-LAST:event_jBconsultarActionPerformed

    private void jBactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinsertarActionPerformed
        // TODO add your handling code here:
        
        // 1. recuperamos los datos ingresados y los almacenamos en un DTO
        String codigo = jTcodigo.getText();
        String nombre = jTnombre.getText();
        String ciudad = jTciudad.getText();
        String pais = jTpais.getText();
        
        AeropuertoDTO objAeropuerto = new AeropuertoDTO();
        objAeropuerto.setCodigo(codigo);
        objAeropuerto.setNombre(nombre);
        objAeropuerto.setCiudad(ciudad);
        objAeropuerto.setPais(pais);
        
        // 2. invocamos el metodo insertar
        AeropuertoImpl impl = new AeropuertoImpl(); 
        int res=impl.actualizarAeropuerto(objAeropuerto);
        
        // 2. insertamos un nuevo aeropuerto
        
        if(res==1){
            jTAtodo.setText("registro exitoso!");
        }
        
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVerTodo;
    private javax.swing.JButton jBactualizar;
    private javax.swing.JButton jBconsultar;
    private javax.swing.JButton jBinsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAtodo;
    private javax.swing.JTextField jTciudad;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTnombre;
    private javax.swing.JTextField jTpais;
    // End of variables declaration//GEN-END:variables
}
